export enum ArticlesActionTypes {
    GET_ALL_ARTICLES_STARTED = "GET_ALL_ARTICLES_STARTED",
    GET_ALL_ARTICLES_SUCCESS = "GET_ALL_ARTICLES_SUCCESS",
    GET_ALL_ARTICLES_FAILED = "GET_ALL_ARTICLES_FAILED",

    GET_ARTICLE_BY_ID_STARTED = "GET_ARTICLE_BY_ID_STARTED",
    GET_ARTICLE_BY_ID_SUCCESS = "GET_ARTICLE_BY_ID_SUCCESS",
    GET_ARTICLE_BY_ID_FAILED = "GET_ARTICLE_BY_ID_FAILED",

    GET_ALL_INFORMATIONS_STARTED = "GET_ALL_INFORMATIONS_STARTED",
    GET_ALL_INFORMATIONS_SUCCESS = "GET_ALL_INFORMATIONS_SUCCESS",
    GET_ALL_INFORMATIONS_FAILED = "GET_ALL_INFORMATIONS_FAILED",
}